# Generated by Django 2.2.5 on 2020-09-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0002_post_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='first_name',
        ),
    ]
