# Generated by Django 2.2.5 on 2020-09-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_remove_post_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='My personal Blog', max_length=255),
        ),
    ]
