# Generated by Django 2.2.5 on 2020-09-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0008_auto_20200921_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='click here to read full article', max_length=255),
        ),
    ]
